### ISSUE TITLE
USER STORY: Register

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/pp5_spa_e-commerce#16]
As a **user** I can **register as a user ** so that **I can create a user profile so that I can see my bookings and receive the benefits of being a member**.

# Acceptance Criteria

- Acceptance criteria 1: Use Allauth registration.

- Acceptance criteria 2: Add Customer profile (phone, city, date of birth).

- Acceptance criteria 3: The user gets a confirmation email and can log-in after confirmation.

# Tasks

- [x] Task 1: Add allauth registration.
- [x] Task 2: Add send email after registration.
- [x] Task 3: The user can login after registration.
- [x] Task 4: Add Customer profile.

**Comment by CeciliaSG** [comment]
Done
