### ISSUE TITLE
USER STORY: (For Staff) Manage Availability from the front-end

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/pp5_spa_e-commerce#17]
As  **staff** I can manage dates and time slots for spa services easily by logging in on the site **(by choosing to add or delete time slots to dates (already created in the backend admin))** so that I don't need to access the admin**

# Acceptance Criteria

- Acceptance criteria 1: Staff can access the manage availability page from the frontend

- Acceptance criteria 2: staff can choose a service and date.

- Acceptance criteria 3: Staff can click and un-click dates to make them available or unavailable.

# Tasks

- [x] Task 1: Add manage Availability page
- [x] Task 2: Add link in nav dropdown to access.
- [x] Task 3: Add possibility to select service, date and time slots.
