### ISSUE TITLE
USER STORY: ADMIN/MANAGE SPA SERVICESVICES, BOOKINGS, DATES AND TIME SLOTS

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/pp5_spa_e-commerce#18]
As **STAFF OR SUPERUSER** I can **access both the frontend and backend admin****so that I can admin/manage spa services, dates, time slots and bookings **.

# Acceptance Criteria

- Acceptance criteria 1: Access backend admin.

- Acceptance criteria 2: Access Frontend admin.

# Tasks

- [x] Task 1: Add link visible only for staff in nav dropdown.
- [x] Task 2: Create backend admin to handle adding and deleting service, adding and deleting dates, adding and delting time .slots.
- [x] Task 3. Create admin that can manage spa bookings: deleting, adding to and updating existing bookings.
- [x] Task 4. Try and speed up loading of admin..
