### ISSUE TITLE
USER STORY: Add purchases to cart and checkout/pay

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/pp5_spa_e-commerce#4]
- As a customer/user I want to be able to select services, date (and quantity when applicable)  so that I can add them to the cart.
- As a customer/user I want to be able to pay for my selected services and receive a confirmation of my booking/purchase.
- As a customer I want to be able to delete, increase quantity and update my cart before going to checkout and payment.
- 
# Acceptance Criteria

- Acceptance criteria 1: The user can access the cart after adding a service.
- Acceptance criteria 2: The user can add, change and delete service in the cart.
-  Acceptance criteria 3: The user can add services to the cart when on the booking page.

# Tasks

- [x] Task 1: create booking page.
- [x] Task 2: Create possibility to choose service, date and time slot (quantity only applicable to spa_access).
- [x] Task 3: Create possibility to add to cart.
- [x] Task 4: Create possibility to add further services, change quantity and delete services when already added to the cart.
- [x] Task 5: Create possibility to add to cart.
