### ISSUE TITLE
USER STORY: Logout; change of mind when logging out

### ISSUE THREAD

**Issue by CeciliaSG** [CeciliaSG/pp5_spa_e-commerce#8]
As a **user** I can **find a password recovery link on the login page ** so that **that I can easily recover my password**

# Acceptance Criteria

- Acceptance criteria 1: A link to password recovery page.
- Acceptance criteria 2: A password recovery email is sent to the user.
-  Acceptance criteria 3: The password is reset.

# Tasks

- [x] Task 1: Add link.
- [x] Task 2: Check that email is sent.
- [x] Task 3: Check that password is reset.
